// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class VVAuthorityAction;

@interface VVAuthorityAction : NSObject
@property(nonatomic, copy, nullable) NSString * action;
@end

@protocol VVFlutterLoginAuthority
-(void)notifyAuthorityAction:(VVAuthorityAction*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void VVFlutterLoginAuthoritySetup(id<FlutterBinaryMessenger> binaryMessenger, id<VVFlutterLoginAuthority> _Nullable api);

NS_ASSUME_NONNULL_END
