// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "VVFlutterLoginAuthority.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = [NSDictionary dictionaryWithObjectsAndKeys:
        (error.code ? error.code : [NSNull null]), @"code",
        (error.message ? error.message : [NSNull null]), @"message",
        (error.details ? error.details : [NSNull null]), @"details",
        nil];
  }
  return [NSDictionary dictionaryWithObjectsAndKeys:
      (result ? result : [NSNull null]), @"result",
      errorDict, @"error",
      nil];
}

@interface VVAuthorityAction ()
+(VVAuthorityAction*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation VVAuthorityAction
+(VVAuthorityAction*)fromMap:(NSDictionary*)dict {
  VVAuthorityAction* result = [[VVAuthorityAction alloc] init];
  result.action = dict[@"action"];
  if ((NSNull *)result.action == [NSNull null]) {
    result.action = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.action ? self.action : [NSNull null]), @"action", nil];
}
@end

void VVFlutterLoginAuthoritySetup(id<FlutterBinaryMessenger> binaryMessenger, id<VVFlutterLoginAuthority> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.FlutterLoginAuthority.notifyAuthorityAction"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        VVAuthorityAction *input = [VVAuthorityAction fromMap:message];
        [api notifyAuthorityAction:input error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
