// Autogenerated from Pigeon (v0.1.17), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.flutter.communication;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;
import java.util.ArrayList;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings("unused")
public class VVFlutterLoginAuthority {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class AuthorityAction {
    private String action;
    public String getAction() { return action; }
    public void setAction(String setterArg) { this.action = setterArg; }

    HashMap toMap() {
      HashMap<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("action", action);
      return toMapResult;
    }
    static AuthorityAction fromMap(HashMap map) {
      AuthorityAction fromMapResult = new AuthorityAction();
      Object action = map.get("action");
      fromMapResult.action = (String)action;
      return fromMapResult;
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface FlutterLoginAuthority {
    void notifyAuthorityAction(AuthorityAction arg);

    /** Sets up an instance of `FlutterLoginAuthority` to handle messages through the `binaryMessenger` */
    static void setup(BinaryMessenger binaryMessenger, FlutterLoginAuthority api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.FlutterLoginAuthority.notifyAuthorityAction", new StandardMessageCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            HashMap<String, HashMap> wrapped = new HashMap<>();
            try {
              @SuppressWarnings("ConstantConditions")
              AuthorityAction input = AuthorityAction.fromMap((HashMap)message);
              api.notifyAuthorityAction(input);
              wrapped.put("result", null);
            }
            catch (Exception exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static HashMap wrapError(Exception exception) {
    HashMap<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", null);
    return errorMap;
  }
}
